name: Locize namespaces

on:
  pull_request:
    branches: ['main']

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}

jobs:
  validate:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2 # Update to v2
      - name: Setup Node.js
        uses: actions/setup-node@v2 # Update to v2
        with:
          node-version: 16

      - name: Clone Mobile app
        run: |
          git clone https://github.com/Hostlife22/mobile.git mp_app_mobile

      - name: Copy Changes to Mobile app
        run: |
          cp -r src/locales/en mp_app_mobile/locales/en

      - name: Typecheck in Mobile app
        run: |
          cd mp_app_mobile
          yarn install
          yarn typecheck
