name: Check locize namespaces

on:
  pull_request:
    branches:
      - 'main'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  validate:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout private tools
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          repository: mobile

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Check for Locale Changes
        id: check_locale_changes
        run: |
          LOCALE_CHANGES=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }}/files" | jq -r '.[] | select(.filename | startswith("src/locales/en/")) | .filename')
          if [[ -n "$LOCALE_CHANGES" ]]; then
            echo "::set-output name=locale_changes::true"
          else
            echo "::set-output name=locale_changes::false"
          fi

      # - name: Setup SSH
      #   if: steps.check_locale_changes.outputs.locale_changes == 'true'
      #   run: |
      #     install -m 600 -D /dev/null ~/.ssh/id_rsa
      #     echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
      #     host='github.com'
      #     hosts="$(dig +short "$host" | grep -v '\.$' | sed -z 's|\n|,|g')$host"
      #     ssh-keyscan -H "$hosts" > ~/.ssh/known_hosts

      - name: Clone Mobile App
        if: steps.check_locale_changes.outputs.locale_changes == 'true'
        run: |
          git clone git@github.com:Hostlife22/mobile.git

      - name: Copy Locale Changes to Mobile App
        if: steps.check_locale_changes.outputs.locale_changes == 'true'
        run: |
          rsync -av src/locales/en/ mobile/src/locales/en/

      - name: Typecheck Mobile App
        if: steps.check_locale_changes.outputs.locale_changes == 'true'
        run: |
          cd mobile
          yarn install
          yarn typecheck
