name: Locize namespaces

on:
  pull_request:
    branches: ['master']

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}

jobs:
  validate:
    runs-on: ubuntu-20.04
    steps:
      # https://github.com/actions/checkout/commit/2541b1294d2704b0964813337f33b291d3f8596b
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # pin@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/

      # https://cli.github.com/manual/gh_api
      - name: Find dot in translation keys
        run: |
          find_dot () {
            find src/locales/en -name '*.json' -type f \
              -exec jq -e '
                paths | join(" -> ") | select(test("\\.")) | (input_filename + " -> " + .)
              ' -- {} \;
          }
            
          show_result () {
            echo -e "Dot in translation key is not recommended.\nPlease use nested object instead."
            echo -e "Files:"
            echo "$1"
            echo "Docs: https://www.i18next.com/translation-function/essentials#accessing-keys"
            exit 1
          }

          ns=$(find_dot)

          [ -z "$ns" ] || show_result "$ns"

      - name: Clone Mobile app
          run: |
          git clone https://github.com/dknmz/mp_app_mobile.git mp_app_mobile

      - name: Copy Changes to Mobile app
        run: |
          cp -r src/locales/en mp_app_mobile/assets/locales/en

      - name: Typecheck in Mobile app
        run: |
          cd mp_app_mobile
          yarn install
          yarn typecheck
