name: Check locize namespaces

on:
  pull_request:
    branches:
      - 'main'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}


jobs:
  validate:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with: 
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Check for Locale Changes
        id: check_locale_changes
        run: |
          LOCALE_CHANGES=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }}/files" | jq -r '.[] | select(.filename | startswith("src/locales/en/")) | .filename')
          if [[ -n "$LOCALE_CHANGES" ]]; then
            echo "::set-output name=locale_changes::true"
          else
            echo "::set-output name=locale_changes::false"
          fi

      - name: Configure Git
        if: steps.check_locale_changes.outputs.locale_changes == 'true'
        run: |
          git config --global user.email "sima.serafim2021@mail.ru"
          git config --global user.name "Hostlife22"
          
      - name: Clone Mobile App
        if: steps.check_locale_changes.outputs.locale_changes == 'true'
        run: |
          git clone https://Hostlife22:${PERSONAL_ACCESS_TOKEN}@github.com/Hostlife22/mobile.git



      - name: Copy Locale Changes to Mobile App
        if: steps.check_locale_changes.outputs.locale_changes == 'true'
        run: |
          rsync -av src/locales/en/ mobile/src/locales/en/

      - name: Typecheck Mobile App
        if: steps.check_locale_changes.outputs.locale_changes == 'true'
        run: |
          cd mobile
          yarn install
          yarn typecheck
