name: Locize namespaces

on:
  pull_request:
    branches:
      - 'main'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  validate:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install GitHub CLI
        run: |
          curl -sSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list
          apt update
          apt install gh

      - name: Get changed files
        id: get_changed_files
        run: |
          CHANGED_FILES=$(gh pr diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^src/locales/en/' || true)
          echo "::set-output name=files::$CHANGED_FILES"

      - name: Clone Mobile app
        if: steps.get_changed_files.outputs.files != ''
        run: |
          git clone https://github.com/Hostlife22/mobile.git

      - name: Copy Changes to Mobile app
        if: steps.get_changed_files.outputs.files != ''
        run: |
          rsync -av src/locales/en/ mobile/src/locales/en/

      - name: Typecheck in Mobile app
        if: steps.get_changed_files.outputs.files != ''
        run: |
          cd mobile
          yarn install
          yarn typecheck
